### ISSUE TITLE
Secret token mismatch

### ISSUE THREAD

**Issue by utpal4job** [sproctor/php-calendar#117]
Hello, I have installed the script. Now when trying to create event then below error is appearing. Please tell me how to solve the below issue.

---

Secret token mismatch. Possible request forgery attempt.
Backtrace
    calendar.php(735): soft_error('Secret token mismatch. Possible request forgery attempt.')
    event_form.php(318): verify_token()
    event_form.php(31): process_form()
    calendar.php(694) : eval()'d code(1): event_form()
    calendar.php(694): eval()
    calendar.php(621): do_action()
    index.php(81): display_phpc()

---

An early response is always appreciated..

Regards,

**Comment by sproctor** [comment]
Old issue, closing. Re-open if the problem persists
