### ISSUE TITLE
Extending URL Parameters

### ISSUE THREAD

**Issue by willyd61** [sproctor/php-calendar#118]
I am looking at extending the URL parameters to include a new column I added to the occurrences table, its a status field that I would like to give the ability to filter the current view the end user is looking at. I see multiple functions that would likely need to be modified such as display_month. I am wondering if this is the easiest route to take. 

I placed links on the calendar.php file to display each unique status below the calendar name, the idea is to click this status and it sends status=xxx to the current URL, which I have coded and updates the URL to include this like http://ebsweb/cmgcalendar/index.php?action=display_month&year=2014&month=9&day=5&status=new 

Any help on this would be much appreciated and I can send the code I end up with back to you for future users that might want to include custom fields for their calendar records with ability to filter on these. 

Regards, 
Will L.

**Comment by sproctor** [comment]
This is going to be part of v3, so I'm closing this issue as the work is done, but won't be available until that release is available.
