### ISSUE TITLE
Problem with "Add Occurrence"

### ISSUE THREAD

**Issue by murulimadhav** [sproctor/php-calendar#120]
Hi,
 I downloaded php-calendar and installed in my pc. And I am facing a small error. It is I created a event and  after that when i click " Add -Occurance"  without changing any date or time as it is, its submitting this occurance date as "2016 may" . And this is not happening  in your website's demo page . Is there any trouble in my installation ? or is there any settings i am missing in my installation?
 yours faithfully
Murulimadhav

**Comment by sproctor** [comment]
"Add Occurrence" should create an additional occurrence. Can you send me a link to the calendar and give me steps to repeat this?

**Comment by sproctor** [comment]
No response, closing
