### ISSUE TITLE
Error Message for PHP Calendar

### ISSUE THREAD

**Issue by stephensdavis** [sproctor/php-calendar#122]
All of a sudden my PHP Calendar doesn't work.  When I try to log in, I get the following message:

> There was an error connecting to the mySQL database.

Please check the database settings in the 'config.inc.php' file and try again.

The error was reported as:
Access denied for user 'dousman'@'localhost' (using password: YES)
Access denied for user 'dousman'@'localhost' (using password: YES)

Please advise.
Steve Davis

**Comment by sproctor** [comment]
No response. Closing.
