### ISSUE TITLE
group  quickly find

### ISSUE THREAD

**Issue by aa123aa1** [sproctor/php-calendar#123]
When the group has a lot of time, we want to be able to quickly find want group published the calendar, this can let the administrator can quickly locate, shows only need group, thus screening out.

**Comment by aa123aa1** [comment]
where to download Version: 2.1 ?

**Comment by aa123aa1** [comment]
Error
Error in get_fields

Table 'calendar.phpc_fields' doesn't exist
SQL query: SELECT `name`, `required`, `format`, `cid`, `fid`
FROM `phpc_fields`
WHERE `phpc_fields`.`cid` = '1'
Backtrace

phpcdatabase.class.php(372): db_error('Error in get_fields', 'SELECT `name`, `required`, `format`, `cid`, `fid` FROM `phpc_fields` WHERE `phpc_fields`.`cid` = '1' ')
phpccalendar.class.php(160): get_fields('1')
cadmin.php(236): get_fields()
cadmin.php(38): field_list()
calendar.php(704) : eval()'d code(1): cadmin()
calendar.php(704): eval(...)
calendar.php(627): do_action()
index.php(103): display_phpc()

**Comment by aa123aa1** [comment]
i am using  2.0 and now want to use some functions:
i crate category and see it is  &catid=1 ,and i use it into URL, but can't show anything.
http://localhost:1108/php-calendar-2.0/index.php?action=display_month&phpcid=1&month=12&year=2014&catid=1

so ,if i have 10 category and different color , when 10 category use in one month or one day, it shows very more color and messy,so i want to select one  category to see . use &catid=  or other method ? 

how to do it ?
thanks.
I am waiting for your reply。

**Comment by sproctor** [comment]
somewhere around https://github.com/sproctor/php-calendar/blob/v2.0.x/includes/display_month.php#L95 you could add:

    if(!empty($vars['catid']) && $vars['catid'] != $event->catid)
        continue;

You could also use gid instead of catid if you wanted to be able to filter by group id. This is completely untested, but I believe it should work. If this works for you and you want it in 2.1 by default, let me know.

Also, 2.1 is not ready for use currently.

**Comment by sproctor** [comment]
Forgot something. You also need to add $vars to the list of globals at https://github.com/sproctor/php-calendar/blob/v2.0.x/includes/display_month.php#L77

**Comment by aa123aa1** [comment]
Thank you very much for such a rapid recovery, have according to your method to achieve success, and I am really sorry so late reply to your message! Thank you once again。

**Comment by aa123aa1** [comment]
I found the administrator in the background for the user cannot change password, how does this function?how should add? Thank you.The administrator can conveniently set the user password, this function may still need. use 2.0

**Comment by aa123aa1** [comment]
this is 2.1 some wrong:




when i modify the event , it show the wrong . i think 2.1 now is not ok . when the bug is all ok , please let me know , thanks.

**Comment by aa123aa1** [comment]
2.1  i download here :https://github.com/sproctor/php-calendar/archive/master.zip
 when i install it in my  localhost , it can't creat mysql data for  table : phpc_event_fields, then can't run . but i setup 2.0 is very good in my localhost . thanks.

**Comment by aa123aa1** [comment]
other :http://localhost:1108/php-calendar-2.0/index.php?phpcid=1&action=display_week  , how to use display_week in website?  now  display week can't use . or where use display week link ?

**Comment by sproctor** [comment]
2.1 isn't ready for use. The installer hasn't been updated. I'll create a new bug report for the issue that you mentioned though.

**Comment by aa123aa1** [comment]
thanks ,  i want need 2.0 administrator can change  user password,

**Comment by sproctor** [comment]
I've opened a new issue for this.
