### ISSUE TITLE
Embeding Calendar

### ISSUE THREAD

**Issue by theriou** [sproctor/php-calendar#128]
When using embed_setup.php and embed.php includes to embed the calendar into a pre existing layout (like was done in 2.0.8) there is a PHP Error in embed_setup.php of unknown function phpc_html_escape on line 39 which is this line: $phpc_script = phpc_html_escape($_SERVER['PHP_SELF']);

Changing this back to htmlentities seems to makes this method work fine like it used to be

**Comment by sproctor** [comment]
What version are you using? The main git line is not ready for use. Get 2.0.9 from here. https://github.com/sproctor/php-calendar/releases If that is what you're using, then I must have made a mistake there.

**Comment by theriou** [comment]
It is from the 2.0.9 zip file on that link

**Comment by sproctor** [comment]
Ah, thanks. Sorry, I forgot to add an include for that function. I've committed fc002a8 which should fix the issue.

**Comment by theriou** [comment]
With that put in it works fine, thanks!
