### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by piras** [sproctor/php-calendar#133]
Why when I open " calendar " shows all the characters to the right of the screen and the graphics are not present?
![shot](https://cloud.githubusercontent.com/assets/12071565/7280365/7ea2fe34-e922-11e4-9060-c8b532d917da.png)

**Comment by sproctor** [comment]
The stylesheet and possibly scripts aren't loading. HTML would be better.

**Comment by piras** [comment]
I have updated the browser (Mozilla Firefox ver.37) and now works well

**Comment by piras** [comment]
Unfortunately there is something wrong .
I have installed a webserver (xampp ver .5.6.8 for Windows) on a machine in  lan (this is not connected to the Internet) along with "php-calendar 2.0.9" : now if I open "php-calendar" the machine running xampp with the same browser (mozilla ver.37.0.2 ) these displays the image that I have posted, but if I open the same page from another computer it displayed correctly: why?
