### ISSUE TITLE
Embeding error

### ISSUE THREAD

**Issue by cschatzman** [sproctor/php-calendar#134]
Hi,
After I recently updated php-calendar from version 2.0 to 2.0.9 and followed the typical embedding routine I received this error:

Fatal error: Call to undefined function phpc_html_escape() in "path/to/php-calendar-2.0.9/includes/embeded_setup.php on line 39

I have tried an include("path/to/includes/utils.php") where the phpc_html_function resides. I then received a "Hacking attempt" message. 

Please advise how to correct this error with compromising the security of the calendar? 

Thank You

**Comment by theriou** [comment]
it is fixed if you manually do this commit: https://github.com/sproctor/php-calendar/commit/fc002a857476d1f1f725e93007a08dd30355dd64

as seen in closed issue https://github.com/sproctor/php-calendar/issues/128
