### ISSUE TITLE
dbversion.php not in git

### ISSUE THREAD

**Issue by Infern1** [sproctor/php-calendar#135]
Line 32 in install.php

```
require_once("$phpc_includes_path/dbversion.php");
```
However there is no file dbversion.php

**Comment by dogatemycomputer** [comment]
I am having the same issue.   I don't know what the format of the file should be and I can't find another copy anyplace else.

**Comment by sabas** [comment]
Could you try removing that line?

**Comment by dogatemycomputer** [comment]
Yeah.  I just figured that out.  :-)

**Comment by sabas** [comment]
It's working? If it is I remove it from master branch :-)

**Comment by dogatemycomputer** [comment]
Yes.  Once I removed that line and completed the install wizard the calendar software works great.  Already created a couple of calendars.

**Comment by sabas** [comment]
Thanks!
