### ISSUE TITLE
Events not showing to public

### ISSUE THREAD

**Issue by pararrayos** [sproctor/php-calendar#137]
Hi there. Despite configuring public permissions to see events but not to write, and after creating a pair of test events with a logged user, if I log out I can't see them. Why is that? Is it a bug?

**Comment by pararrayos** [comment]
Just realized that the described above only happens when a user belongs to a group. If not, the events are showing to public.

**Comment by sproctor** [comment]
Ancient issue. If this is still happening in the most recent version, please let me know.
