### ISSUE TITLE
Create an event automatically

### ISSUE THREAD

**Issue by HopedWall** [sproctor/php-calendar#139]
Hi, is it possible to create an event automatically? I'm working on a small website which handles projects for a small business; each project has a start date and an end date and I'd like to show them all on a calendar. Thanks in advance for all the answers! (Sorry if the question is stupid but I've started learning PHP a few days ago).

**Comment by sproctor** [comment]
Hi! I'm sorry for being unresponsive. I just resumed work here in earnest a few days ago. There is no scripting feature to add events. You could write a script to add events to the DB, unfortunately I don't think there's any way to add that functionality to the calendar unless the events being added are in some standard format. I'm planning to support some of those eventually, but currently do not.
