### ISSUE TITLE
SERVER_NAME and SERVER_PORT not always defined

### ISSUE THREAD

**Issue by oneisgarbage** [sproctor/php-calendar#140]
PHP Notice:  Undefined index: SERVER_NAME in /var/www/cal/php-calendar-2.0.9/includes/embed_setup.php on line 45
PHP Notice:  Undefined index: SERVER_PORT in /var/www/cal/php-calendar-2.0.9/includes/embed_setup.php on line 51

**Comment by sproctor** [comment]
Closing old issues. If you're still experiencing this, please re-open.
