### ISSUE TITLE
Embedding headach

### ISSUE THREAD

**Issue by 1EyeTy** [sproctor/php-calendar#144]
I know that the directions say it is easy but I cannot get this to work no matter what I do. I have tried every type of include statement I can think of since I think that might be the issue. As you can see from the file the calendar is not showing. No error. I open index.php calendar and it works but not the embed.

Using wamp: site address:http://localhost/newauthorsite/twbarton_com/Includes
actual file location : C:\wamp64\www\newauthorsite\twbarton_com\includes

Any help would be appreciated.

![phpcalendar](https://cloud.githubusercontent.com/assets/19857046/18616420/5a57f118-7d89-11e6-9018-eaa6e351d4cf.png)

**Comment by 1EyeTy** [comment]
Ok, so I changed the page from html to php to see what the heck is going on and I at least have something.
Code>

**Comment by vb078** [comment]
Exacltly the same here (Firefox user, Php up to date)

**Comment by theriou** [comment]
You need to manually do this commit: https://github.com/sproctor/php-calendar/commit/fc002a857476d1f1f725e93007a08dd30355dd64

as seen in fixed issue https://github.com/sproctor/php-calendar/issues/128

**Comment by Revo86** [comment]
my page is completely white besides the title even after the fix.

**Comment by sproctor** [comment]
This should be fixed in 2.0.10. If you're getting a blank page, it's because PHP is set to not display errors and you'll need to check your logs.
