### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by JackFrost10** [sproctor/php-calendar#145]
Fatal error: Call to a member function get_language() on a non-object in \includes\setup.php on line 145

I installed it before and it worked fine,

**Comment by sproctor** [comment]
I don't see how this is possible. If the user can't be created, it shouldn't get to that line. Did you modify setup.php at all? If you can still reproduce this let me know.

**Comment by JackFrost10** [comment]
Hi, I found the problem, the default language on the database is modified for the anonymous account I fixed the error by creating a fresh database,
