### ISSUE TITLE
Can't get Calendar embed to display properly

### ISSUE THREAD

**Issue by BigZ1981** [sproctor/php-calendar#147]
Hello,
   I'm having issues with the embed.  I did the commit so the embed now displays the calendar, but it doesn't display properly...seems like it's not pulling from the theme CSS file.  I'm a novice PHP programmer, so if you can point me in the right direction on what part of the code could be keeping it from pointing there, it would be greatly appreciated.  It displays perfectly fine in the calendar index.  It's the embed that's having the display issues.

www.gracecathedralsa.org/calendar.php

**Comment by theriou** [comment]
It seems like you are missing the /static folder? That contains the js, images, css, etc for calendar, I believe.

**Comment by BigZ1981** [comment]
I see.  Since the calendar was installed in its own directory, and I have the embed in the main directory, it kills the call path for the embed code.  I put a copy of the static directory in the main directory for now as a temporary fix, but what part of the embed or embed setup code can I edit to change the path & avoid having this copy of the static directory?

**Comment by sproctor** [comment]
I guess there should be a variable to set the location of the static directory on the server. Unfortunately there is not. You can edit line 40 of embed.php and change "static" to "php-calendar/static" or wherever you want to have that directory. https://github.com/sproctor/php-calendar/blob/master/includes/embed.php#L40

**Comment by ianhaney** [comment]
Hi BigZ1981

Can you help me with embedding the calendar please as on the site I am developing, I got the calendar in it's own folder called events and am trying to embed the calendar into the main index.php in the root but it;s being messed up. I have attached a screenshot if can help please as on your link it looks perfect

![calendar-embed-issue](https://cloud.githubusercontent.com/assets/16349093/26397162/472367a6-406d-11e7-979a-5182f5ebe14d.jpg)
