### ISSUE TITLE
$Week_of_Year

### ISSUE THREAD

**Issue by maheba544** [sproctor/php-calendar#148]
is there a really simple way of changing this, so the numbers 1-8 appear instead of the weeks of the year

**Comment by jbteixeir** [comment]
I needed this to work when the week started on monday, so I've just added an if to suit my case.
Display_week.php line 44
`  if((day_of_week(1, 1, $year)) == 6){
    $day_of_year = 2 + ($week_of_year - 1) * 7;
  }
  else{
    $day_of_year = 1 + ($week_of_year - 1) * 7 - (day_of_week(1, 1, $year));
  }`

**Comment by sproctor** [comment]
I don't understand the request. Where do you want the numbers 1 to 8 displayed?

**Comment by sproctor** [comment]
No response, closing
