### ISSUE TITLE
Select calendar dropdown not showing in embedded

### ISSUE THREAD

**Issue by Nvezz** [sproctor/php-calendar#150]
Hello,

Maybe I am doing something wrong but when I embed the calendar in a page i don't see the dropdown Icon to change the calendar.

Here is the demo:

Embedded page: http://www.eliplay.it/club/calendario.php
![image](https://cloud.githubusercontent.com/assets/27565225/25064496/a2e5ad28-21fb-11e7-80f7-68a82050384f.png)

Complete calendar: http://www.eliplay.it/club/calendar/index.php
![image](https://cloud.githubusercontent.com/assets/27565225/25064499/b7209d70-21fb-11e7-90b5-d6d2e29266d9.png)

Thanks

**Comment by sproctor** [comment]
This is fixed by commit 36bf578 and will be included in the next release. Thanks for your report.
