### ISSUE TITLE
Calendar switches on some urls from https to http

### ISSUE THREAD

**Issue by Jumpy91** [sproctor/php-calendar#151]
Hey,

i love the simplity of your calendar.

Im expiring the error, that on some links (eg. switching months, clicking the headline, etc.) the https goes away. Hope there is a simple fix for that.

Greetings,
Jumpy

**Comment by sproctor** [comment]
I'm not experiencing this. I tested on 2.0.10 here: https://www.php-calendar.org/php-calendar-2.0/

Can you provide a link where this is reproducible?

**Comment by Jumpy91** [comment]
Just take a look at this page https://kalender.emm.mobi/index.php .

**Comment by sproctor** [comment]
Is your page behind a proxy server? The bit of code that determines the protocol used in URLs is here: https://github.com/sproctor/php-calendar/blob/master/index.php#L46

**Comment by Jumpy91** [comment]
Yes, the page is running behind a haproxy used to run multiple services behind one ip.

**Comment by sproctor** [comment]
You need to make sure HAProxy is adding "X-Forwarded-Proto: https" to the headers for SSL requests.

**Comment by Jumpy91** [comment]
Thanks for your reply. Fixed the issue. Thanks for giving me the tipp using the header string.
