### ISSUE TITLE
embed issue

### ISSUE THREAD

**Issue by ianhaney** [sproctor/php-calendar#152]
Hi

I have embedded the calendar into a website I am developing but it seems to be doing some weird thing down the left, it looks like the navigation to select the different years and months, I have attached a screenshot

![calendar-embed-issue](https://cloud.githubusercontent.com/assets/16349093/26394172/f40ac5ae-4063-11e7-89ca-cb2347c6cc0d.jpg)

Can anyone help please?

The site is https://www.broadwaymediadesigns.co.uk/sites/the-black-dog-one/index.php#events

Thank you in advance

**Comment by sproctor** [comment]
I'd guess that you had some conflicting CSS there. Without seeing the source, it's hard to say. It seems that you've found another solution, so I'm closing this issue.
