### ISSUE TITLE
Unknown column 'password_editable' in 'field list'

### ISSUE THREAD

**Issue by nathanzachary** [sproctor/php-calendar#155]
Hi Sean,

Thanks again for the fix in issue #154.  I was able to update my calendar.  However, now I'm facing another problem in that I can't login.  Previously, I didn't have a log in at all, so I never created a username and password (that I recall, anyway).  Now, when I try to log in, I get the following trace:

```
Error
Error getting user.

Unknown column 'password_editable' in 'field list'
SQL query: SELECT `caldb_users`.`uid`, `username`, `password`, `caldb_users`.`admin`, `password_editable`, `timezone`, `language`
FROM caldb_users
WHERE username='zach'
Backtrace
#0 /var/www/domains/DOMAIN/cal/htdocs/includes/phpcdatabase.class.php(714): PhpcDatabase->db_error('Error getting u...', 'SELECT `caldb_u...')
#1 /var/www/domains/DOMAIN/cal/htdocs/includes/calendar.php(91): PhpcDatabase->get_user_by_name('zach')
#2 /var/www/domains/DOMAIN/cal/htdocs/includes/login.php(36): login_user('zach', 'PASSWORD')
#3 [internal function]: login()
#4 /var/www/domains/DOMAIN/cal/htdocs/includes/calendar.php(846): call_user_func('login')
#5 /var/www/domains/DOMAIN/cal/htdocs/includes/calendar.php(777): do_action()
#6 /var/www/domains/DOMAIN/cal/htdocs/index.php(73): display_phpc()
#7 {main}
```

I removed the actual password in line #2 of the backtrace.

I see the following columns in the caldb_users table:

```
MariaDB [caldb]> SELECT * FROM caldb_users;
+-----+----------+----------------------------------+-------+
| uid | username | password                         | admin |
+-----+----------+----------------------------------+-------+
|   1 | zach     | PASSWORD_HASH |     1 |
+-----+----------+----------------------------------+-------+
1 row in set (0.00 sec)
```

As above, I removed the password hash from that output.

So it doesn't look like there is a 'password_editable' column.

Any thoughts?  If there is another way to get a clean installation but still have my previously-stored events, I'm happy to do that as well.

Thanks again for your help.

Cheers,
Nathan Zachary

**Comment by sproctor** [comment]
Sorry, I missed the users table for some reason. I guess I didn't actually try logging in with an updated calendar. I'll try to be a bit more responsive in the future.

```
ALTER TABLE `caldb_users`
ADD `password_editable` tinyint(1) NOT NULL DEFAULT '1',
ADD `timezone` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
ADD `language` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
ADD `gid` int(11)
```

This is fixed by commit 7daa12e72d7ad5f0f83d02bbf61133cba0c334bc I'm about to package up a release that incorporates this change and a very minor improvement to the forms.
