### ISSUE TITLE
depends on google

### ISSUE THREAD

**Issue by ecxod** [sproctor/php-calendar#162]
depends on external scripts …ajax.googleapis.com and cdnjs.cloudflare.com, following this ideea we can completely use googles calendar and do not need this php calendar at all. following the same idea I must start checking the source code if there are no other backdoor.

**Comment by sproctor** [comment]
Sure, you can absolutely use google's calendar if that works for you. If you're paranoid, you could also replace those references with a copy of jquery/jqueryui. Or take it to the next level and don't run any software you haven't written yourself.
