### ISSUE TITLE
Undefined index: QUERY_STRING

### ISSUE THREAD

**Issue by japemete** [sproctor/php-calendar#164]
Hi All,

I have problem with this: Notice: Undefined index: QUERY_STRING in C:\xampp\htdocs\PSC_Dashboard_2\includes\calendar.php on line 583.
Anybody can help me? All help i appreciated

**Comment by sproctor** [comment]
Are you trying to run this on the command line? $_SERVER['QUERY_STRING'] is the query string from the HTTP request. This is mandatory for php-calendar to run.

**Comment by sproctor** [comment]
closing because there was no response
