### ISSUE TITLE
Bug in showing one week

### ISSUE THREAD

**Issue by luotope** [sproctor/php-calendar#167]
I just installed the package and it worked like a charm. The solution is pretty much just what I was looking for. Thanks guys!

I noticed that if I click a week number on the left, it should show that week instead of a whole month. However, the days shown are not from the week you clicked, but from the previous week. For example, if I click week number 16 it should show days 19 to 25 but days from 12 to 18 are shown instead. I suppose this is a small bug?

**Comment by sproctor** [comment]
fixed, will be included in 2.0.13
