### ISSUE TITLE
How to remove possibility for a user to change the password? 

### ISSUE THREAD

**Issue by luotope** [sproctor/php-calendar#168]
I am intending to use the solution as a booking calendar for a group of people in a sports club, kind of a semi closed group. To keep it simple I would not want to maintain a list of users but create only one user and publish the userID and password for these people. In this case anyone signed in with this userID can however change the password of this user.

What should I change to remove this possibility and leave the right only for admin user? I noticed that your Demo solution is made like this.

Thanks in advance!

**Comment by sproctor** [comment]
There's a database column in the user table `password_editable` that you can set to false. There's no ui to change it.

**Comment by luotope** [comment]
Great! Thanks.
