### ISSUE TITLE
Importing events from prior calendar

### ISSUE THREAD

**Issue by bobatwhidbey** [sproctor/php-calendar#169]
I really like this calendar. It was easy to install and works well going forward. I want to import events from a prior calendar. This seemed straight forward, but isn't working. 

When I add events with my keypad, it appears that only the Events table is being affected, so here's what I did. I created a CSV file that mimics the Events table (eid, cid, owner,....mtime) then using phpMyAdmin at my host, I imported the CSV file. All appears good in the Event table with phpMyAdmin's browse function but those events don't show up in my calendar. 

Can you tell me how to import prior events?  Thank you.  bob@uselessbay.us

**Comment by sproctor** [comment]
You also need the occurrences table. Events stores stuff like the name, etc, occurrences stores when the events actually happen.

**Comment by bobatwhidbey** [comment]
Using phpMyAdmin on my host I've added Events and Occurrences using the Import feature, but none of my events appear on the calendar. Can you see my problem?
![occurrences1](https://user-images.githubusercontent.com/13080152/128640909-b71cfc6d-d3f5-4da1-b17b-beb40e5fce30.jpg)
![event1](https://user-images.githubusercontent.com/13080152/128640911-7be4a213-a41b-43d3-b3b2-ba34e96a7896.jpg)

**Comment by bobatwhidbey** [comment]
The events added via phpMyAdmin DO appear when the Search feature of the calendar is used, even though they don't appear on the calendar.

**Comment by sproctor** [comment]
There's a dropdown selector on the title to pick the calendar. Make sure you're looking at the correct calendar. Make sure the max events displayed per day is greater than 0. I'm not sure what else it could be.

**Comment by bobatwhidbey** [comment]
Success, although I'm not 100% sure I know what did it. On Events I switched start_date & end_date with start_ts & end_ts.  I think that was the problem. I also increase the maximum subject length from 50 to 250, since I do have some long subjects. 

It would be good to know what 'start_date", catid, ctime, and mtime mean. What purpose?

**Comment by sproctor** [comment]
ctime and mtime are create/modify times. catid is the category id, for adding colors, etc. start_date and end_date exist because the date is timezone agnostic. start_ts and end_ts are timestamps.

**Comment by bobatwhidbey** [comment]
Thanks Sean

**Comment by bobatwhidbey** [comment]
Is there a way to utilize a SQLite3  DB rather than MySQL

**Comment by sproctor** [comment]
Currently, no. SQLite has it's uses, I'm not sure it's the best DB for the task though. I don't think it has good support for concurrent access. What makes you want to use it instead of MySQL ?

**Comment by bobatwhidbey** [comment]
I can see the benefits of MySQL over SQLite. Here's a problem I'm having:
So many of my repeating events do not fall within the choices that are available. Daily/weekly/monthly rarely handles the situation. I need Every **other** week in one situation but mostly my events seemed to be tied to the nth day of every month, as in  "2nd Monday of the month", or "2nd and 4th Thursdays".  Is there some hope those types of repeating events can be accomodated in the future?

**Comment by bobatwhidbey** [comment]
I was thinking of adding two more check-box lists, to the right of the Repeats list.
1st
2nd
3rd
4th

and a second list:
Sun.
Mon.
.
.
Sat.

The user would need to check one from each column

**Comment by bobatwhidbey** [comment]
To go along with your current approach you might add one more option to the Repeats dropdown (**Nth of the month**). When that option is chosen, the phrase to the right would be : "Repeats on what Thursday of each month". You would get the actual day of the week (Thursday in this example) from the "From Date" on the form.

**Comment by bobatwhidbey** [comment]
One of the features I need for the calendar is the ability to add a recurring event that occurs the N-th Day of selected months. [Book club meets the 2nd Thursday of every month except July and August] I've pretty much accomplished that. See the attached pictures. I haven't figured out how to add a list of check boxes side-by-side, horizontally. Only one on top of each other, vertically, and that won't really work. I'd like 2 rows of 6, or maybe 1 of 12. Can you please suggest some changes to my PHP additions to your code that will accomplish that.
![Event form PHP](https://user-images.githubusercontent.com/13080152/130160783-e7cc46e3-e395-4bbb-bea1-57c8af732829.jpg)
![Event](https://user-images.githubusercontent.com/13080152/130160792-fe6496b5-ee4f-4b0c-9dc1-4969d171da9a.jpg)
don't know how to add

**Comment by sproctor** [comment]
You could make the columns in CSS. I don't know what your compatibility requirements are. You can create a group for the month checkboxes and set a custom class on it. Then in CSS, create a grid. My PHP skills are pretty rusty, if this isn't valid PHP, please forgive me.

```php
$month_group = new FormGroup(class = "month-grid");
for ($i = 1; $i <= 12; $i++) {
    $month_group->add_part("month$i", false, month_names[$i]);
}
$nthly_group->add_part($month_group);
```

then the CSS something like:

```css
.month-grid {
  display: grid;
  grid-template-columns: auto auto;
}

.month-grid .form-checkbox-question {
  // style for the children
}
```

I don't think you actually need more style, but maybe you'll want something to make it look nice.

Good luck and sorry for the awkward custom form stuff. It's a lot easier to read than what I used to have, if that's any consolation.
