### ISSUE TITLE
Add a State to phpcalendar

### ISSUE THREAD

**Issue by kdmiller45** [sproctor/php-calendar#190]
How do I add the State of Kansas in the Americas

Keith

**Comment by sproctor** [comment]
I don't understand this question. What are you trying to add a state to?

**Comment by kdmiller45** [comment]
Try to add the state of Kansas into the default of the America/Kansas time zone

**Comment by sproctor** [comment]
The timezones are generated by PHP, which I assume gets them from your system timezones. You can see a list of timezones here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones I think for Kansas, you want America/Chicago. Closing this issue.
