### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Vacman** [sproctor/php-calendar#192]
Any plans to bring this up to PHP 8 support? Want to pull the rest of my projects up to PHP *, but this is one that will not run on 8.

**Comment by Vacman** [comment]
Well.... it would have helped if I bothered to explore further. Looks like you in fact patch up. Will take a look!

**Comment by sproctor** [comment]
2.0.13 should work on PHP 8. I'll close this issue. Feel free to re-open it if you have any issues.
