### ISSUE TITLE
The demos on the web page point to a non-existing domain

### ISSUE THREAD

**Issue by riihikallio** [sproctor/php-calendar#193]
There are two links to demos pointing to php-calendar.com which doesn't exist.

**Comment by sproctor** [comment]
Thanks for letting me know. php-calendar.com was my old domain name. Moving the hosting to github has messed with my organization a bit. Until I find a better solution, I'm hosting the demos on my personal site. The dev version is currently broken. I'll fix it when the state of the dev code has stabilized a bit more.
