### ISSUE TITLE
Birthday / pictures upload reminders wish

### ISSUE THREAD

**Issue by sanded001** [sproctor/php-calendar#196]
Suggestion / wish for the calendar.

A birthday input - for every year upcoming, sums up the age every year.

And if possible a way to upload pictures as well to the calendar - inside the describtion area etc.

**Comment by sproctor** [comment]
I'm not really understanding the benefit to this. You can already create a birthday event. In the description you can put the birth year. You would just need to do a subtraction to get the age. You could create a special category for birthdays if you want them colored differently.

I'm not sure about file uploads. There are a lot many parameters to consider, and I think it might be too big of a project to build into the calendar. You can upload files elsewhere and include them in the calendar. Just add text like: `![alt text for screen readers](https://example.com/path/to/image.png "Text to show on mouseover")`

**Comment by sproctor** [comment]
Here's an example event with an image: https://www.seanproctor.com/php-calendar-2.0/index.php?action=display_event&phpcid=1&eid=4637

I'm going to close this, because I think it's already possible to do something close enough.
