### ISSUE TITLE
Snyk detected vulnerabilities: SQL Injection and Cross-site Scripting (XSS) in install.php

### ISSUE THREAD

**Issue by akovov** [sproctor/php-calendar#199]
SQL Injection [CWE-89](https://cwe.mitre.org/data/definitions/89.html)
Unsanitized input from an HTTP parameter flows into query, where it is used in an SQL query. This may result in an SQL Injection vulnerability.

lines 467, 486, 689, 784, 794:
`$dbh->query($query)`

Cross-site Scripting (XSS) [CWE-79](https://cwe.mitre.org/data/definitions/79.html)
Unsanitized input from an HTTP parameter flows into the echo statement, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS).

lines 98, 720, 748, 800

**Comment by sproctor** [comment]
install.php should not be accessible after the calendar is installed. It is inherently insecure as it allows access to the DB that no normal user should have. Regardless, it is removed for php-calendar 3 and whenever that version is released Snyk will stop complaining about it. If you disagree with any of this, please feel free to reopen.
